name = "chengqi-agent-app"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
NODE_ENV = "production"
MASTRA_DEFAULT_STORAGE_URL = ":memory:"

# D1 数据库绑定（用于存储 agent 记忆）
# [[d1_databases]]
# binding = "DB"
# database_name = "mastra-db"
# database_id = "your-database-id"

# KV 存储绑定（可选，用于缓存）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-id"

# 构建配置
[build]
command = "npm run build && node scripts/post-process-worker.cjs"

# 开发环境配置
[env.development]
name = "chengqi-agent-app-dev"

# 生产环境配置  
[env.production]
name = "chengqi-agent-app-prod"